<div class="pag" align="center">
   
        <!-- First page link -->
        <?php if (isset($this->previous)): ?>
              <a href="<?= $this->url(array('page' => $this->first)); ?>">Início</a> 
        <?php else: ?>
                <span class="disabled">Início</span> 
        <?php endif; ?>
    
        <!-- Previous page link -->
    
        <?php if (isset($this->previous)): ?>
              <a href="<?= $this->url(array('page' => $this->previous)); ?>">&lt; Anterior</a> 
        <?php else: ?>
            <span class="disabled">&lt; Anterior | </span> 
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a>
            <?php else: ?>
               &nbsp; &nbsp;<span class="disabled"><?= $page; ?> &nbsp; |</span>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
               <a href="<?= $this->url(array('page' => $this->next)); ?>">Próximo &gt;</a> 
        <?php else: ?>
             <span class="disabled">Próximo &gt; |</span> 
        <?php endif; ?>
        <!-- Last page link -->
        <?php if (isset($this->next)): ?>
              <a href="<?= $this->url(array('page' => $this->last)); ?>">Fim</a>
        <?php else: ?>
            <span class="disabled">Fim</span>
        <?php endif; ?>
        <br><span class="pageof">Pág. <?= $this->current; ?> de <?= $this->last; ?></span>
 </div>
