<script type="text/javascript" src="http://cdn.fterceiro.pt/library/plugins/qtip2/jquery.qtip.min.js"></script>
<link rel="stylesheet" type="text/css" href="http://cdn.fterceiro.pt/library/plugins/qtip2/jquery.qtip.min.css"/>
<?php if ($this->auth == "notauth"):?>


<div class="container">

	<div class="container-fluid mywhite">
		<div class="row-fluid">
			<div class="span12 ">
				<div class="alert alert-error" style="margin-top: 20px;">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<h4>Atenção!</h4>
					<p>
						Não tem autorização para aceder a este recurso. <br />Contacte o
						Administrador de sistemas.
					</p>
				</div>
			</div>
		</div>
	</div>
</div>


<?php else:?>
<div class="infooptimus">
		<table>
		    <tr>
		        <td>Edição do Boletim de Análise Nº <?=$this->bolid;?></td>
		    	<td><span id="loading-animation"></span></td>    
		    </tr>
		</table>
</div>
<form id="boletim_completo" method="post" action="/boletim/update">
<?=$this->form->getElement('id')->setDecorators(array('ViewHelper'))->setValue($this->bolid);?>
	<div class="container-fluid">
		<div class="row-fluid">
			<div class="span2">
                <div class="tabbable tabs-left">
					<ul class="nav nav-tabs">
					    <li class="active"><a href="#tab1" data-toggle="tab"><i class="icon-hdd"></i> Dados Optimus</a></li>
						<li><a href="#tab2" data-toggle="tab"><i class="icon-check"></i> Características Controladas</a></li>
						<li><a href="#tab3" data-toggle="tab"><i class="icon-thumbs-up"></i> Decisão Tomada</a></li>
						<li><a href="#tab4" data-toggle="tab"><i class="icon-filter"></i> Amostragem</a></li>
						<li><a href="#tab5" data-toggle="tab"><i class="icon-comments"></i> Observações</a></li>
					</ul>
				</div>
			</div>
			<div class="span10 mywhite">
				<div class="row-fluid">
					<div class="span10">
						<div class="tab-content">
							<div class="tab-pane active space" id="tab1">
							    <p>Dados do Optimus. Alterar se necessário.</p>
								<table class="table table-striped txtsmall">
                        		    <tr>
                        		        <td><i class="icon-briefcase"></i> Obra Nº:</td>
                        		        <td><?=$this->form->getElement('obra')->setDecorators(array('ViewHelper'));?></td>
                        		        <td><i class="icon-user"></i> Cliente:</td>
                            		    <td><?=$this->form->getElement('cliente')->setDecorators(array('ViewHelper'));?></td>
                            		</tr>
                            		<tr>    
                            		    <td><i class="icon-align-justify"></i> Quantidade:</td>
                            		    <td><?=$this->form->getElement('quantidade')->setDecorators(array('ViewHelper'));?></td>
                            		    <td><i class="icon-folder-close"></i> Produto:</td>
                            		    <td><?=$this->form->getElement('produto')->setDecorators(array('ViewHelper'));?></td>
                            		</tr>
                            		<tr>    
                            		    <td><i class="icon-barcode"></i> Código:</td>
                            		    <td><?=$this->form->getElement('codigo')->setDecorators(array('ViewHelper'));?></td>
                            		    <td><i class="icon-list-alt"></i> V/Enc:</td>
                            		    <td><?=$this->form->getElement('encomenda')->setDecorators(array('ViewHelper'));?></td>
                            		 </tr>   
                            	</table>
                            	<div class="txt-optimus-index">
                            	      <table class="table-opt">
                            	          <tr>
                            	              <th><span id="et-th" class="table-opt-click"><i class="icon-eye-open"></i> Especificações Técnicas</span></th>
                            	              <th><span id="ie-th" class="table-opt-click"><i class="icon-eye-open"></i> Instruções Especiais</span></th>
                            	              <th><span id="img-th" class="table-opt-click"><i class="icon-eye-open"></i> Imagem</span></th>
                            	           </tr>
                            	           <tr>
                            	           <td><span id="et"><textarea><?=utf8_encode($this->txt1['sect_text']);?></textarea></span></td>
                            	           <td><span id="ie"><textarea><?=utf8_encode($this->txt2['sect_text']);?></textarea></span></td>
                            	           <td><span id="img"><?=$this->image;?></span></td>
                            	      </table>
                                      
                                    </div>
							</div>
							<div class="tab-pane space" id="tab2">
								<div class="tabbable">
								    <ul class="nav nav-tabs">
                					    <li class="active"><a href="#tab-cc1" data-toggle="tab"><i class="icon-file"></i> Matéria Prima</a></li>
                						<li><a href="#tab-cc2" data-toggle="tab"><i class="icon-tint"></i> Impressão</a></li>
                						<li><a href="#tab-cc3" data-toggle="tab"><i class="icon-map-marker"></i> Corte e Vinco</a></li>
                						<li><a href="#tab-cc4" data-toggle="tab"><i class="icon-resize-full"></i> Fecho Cartonagem</a></li>
                						<li><a href="#tab-cc5" data-toggle="tab"><i class="icon-truck"></i> Acondicionamento</a></li>
                					</ul>
								</div>
								<div class="tab-content">
    								<div class="tab-pane active" id="tab-cc1">
    								    <table class="table table-striped txtsmall">
                                        		<tr>
                                        			<th>1. Mat&eacute;ria Prima</th>
                                        			<th></th>
                                        			<th></th>
                                        		</tr>
                                        		<tr>
                                        			<td class="esp">Tipo:</td>
                                        			<td><?=$this->form->getElement('tipo_txt')->setDecorators(array('ViewHelper'));?></td>
                                        			<td><?=$this->form->getElement('tipo')->setDecorators(array('ViewHelper'));?></td>
                                        		</tr>
                                        		<tr>
                                        			<td class="esp">Gramagem M&eacute;dia (g/m<sup>2</sup>):</td>
                                        			<td><?=$this->form->getElement('gramagem_txt')->setDecorators(array('ViewHelper'));?></td>
                                        			<td><?=$this->form->getElement('gramagem')->setDecorators(array('ViewHelper'));?></td>
                                        		</tr>
                                        		<tr>
                                        			<td class="esp">Espessura M&eacute;dia (mm):</td>
                                        			<td><?=$this->form->getElement('espessura_txt')->setDecorators(array('ViewHelper'));?></td>
                                        			<td><?=$this->form->getElement('espessura')->setDecorators(array('ViewHelper'));?></td>
                                        		</tr>
                                        		<tr>
                                        			<td class="esp">Sentido Fibra</td>
                                        			<td></td>
                                        			<td><?=$this->form->getElement('fibra')->setDecorators(array('ViewHelper'));?></td>
                                        		</tr>
                                        	</table>
    								</div>
    								<div class="tab-pane" id="tab-cc2">
    								    <table class="table table-striped txtsmall">
                                    		<tr>
                                    			<th>2. Impress&atilde;o</th>
                                    			<th></th>
                                    			<th></th>
                                    		</tr>
                                    		<tr>
                                    			<td class="esp">Texto (grafismo / padr&atilde;o aprovado)</td>
                                    			<td></td>
                                    			<td><?=$this->form->getElement('texto')->setDecorators(array('ViewHelper'));?></td>
                                    		</tr>
                                    		<tr>
                                    			<td class="esp">Cores (pantones/ padr&atilde;o aprovado):</td>
                                    			<td><?=$this->form->getElement('cores_txt')->setDecorators(array('ViewHelper'));?></td>
                                    			<td><?=$this->form->getElement('cores')->setDecorators(array('ViewHelper'));?></td>
                                    		</tr>
                                    		<tr>
                                    			<td class="esp">Verniz</td>
                                    			<td></td>
                                    			<td><?=$this->form->getElement('verniz')->setDecorators(array('ViewHelper'));?></td>
                                    		</tr>
                                    		<tr>
                                    			<td class="esp">Qualidade de impress&atilde;o (repintes, sujidades, etc)</td>
                                    			<td></td>
                                    			<td><?=$this->form->getElement('qualidade_impressao')->setDecorators(array('ViewHelper'));?></td>
                                    		</tr>
                                    		<tr>
                                    			<td class="esp">Leitura c&oacute;digo de barras</td>
                                    			<td></td>
                                    			<td><?=$this->form->getElement('codigo_barras')->setDecorators(array('ViewHelper'));?></td>
                                    		</tr>
                                    		<tr>
                                    			<td class="esp">C&oacute;digo Laetus</td>
                                    			<td></td>
                                    			<td><?=$this->form->getElement('codigo_laetus')->setDecorators(array('ViewHelper'));?></td>
                                    		</tr>
                                    		<tr>
                                    			<td class="esp">Tinta reactiva</td>
                                    			<td></td>
                                    			<td><?=$this->form->getElement('tinta_reactiva')->setDecorators(array('ViewHelper'));?></td>
                                    		</tr>
                                    		<tr>
                                    			<td class="esp">C&oacute;digo descodificador</td>
                                    			<td></td>
                                    			<td><?=$this->form->getElement('codigo_descodificador')->setDecorators(array('ViewHelper'));?></td>
                                    		</tr>
                                    		</table>
    								</div>
    								<div class="tab-pane" id="tab-cc3">
    								    <table class="table table-striped txtsmall">
                                        		<tr>
                                        			<td><b>3. Corte e Vinco</b></td>
                                        			<td></td>
                                        			<td></td>
                                        		</tr>
                                        		<tr>
                                        			<td class="esp">Qualidade do corte e vinco (vincos / cortes / picote)</td>
                                        			<td></td>
                                        			<td><?=$this->form->getElement('qualidade_corte_vinco')->setDecorators(array('ViewHelper'));?></td>
                                        		</tr>
                                        		<tr>
                                        			<td class="esp">Dimens&otilde;es da cartonagem:</td>
                                        			<td><?=$this->form->getElement('dimensoes_cartonagem_txt')->setDecorators(array('ViewHelper'));?></td>
                                        			<td><?=$this->form->getElement('dimensoes_cartonagem')->setDecorators(array('ViewHelper'));?></td>
                                        		</tr>
                                        		<tr>
                                        			<td class="esp">Braille</td>
                                        			<td></td>
                                        			<td><?=$this->form->getElement('braille')->setDecorators(array('ViewHelper'));?></td>
                                        		</tr>
                                       </table>
    								</div>
    								<div class="tab-pane" id="tab-cc4">
    								    <table class="table table-striped txtsmall">
                                    		<tr>
                                    			<td><b>4. Fecho da Cartonagem</b></td>
                                    			<td></td>
                                    		</tr>
                                    		<tr>
                                    			<td class="esp">Qualidade da colagem</td>
                                    			<td><?=$this->form->getElement('qualidade_colagem')->setDecorators(array('ViewHelper'));?></td>
                                    		</tr>
                                    		<tr>
                                    			<td class="esp">Funcionamento da cartonagem</td>
                                    			<td><?=$this->form->getElement('funcionamento_cartonagem')->setDecorators(array('ViewHelper'));?></td>
                                    		</tr>
                                    		<tr>
                                    			<td class="esp">Teste de Fric&ccedil;&atilde;o</td>
                                    			<td><?=$this->form->getElement('friccao')->setDecorators(array('ViewHelper'));?></td>
                                    		</tr>
                                    	</table>
    								</div>
    								<div class="tab-pane" id="tab-cc5">
    								    <table class="table table-striped txtsmall">
                                    		<tr>
                                    			<td><b>5. Acondicionamento:</b></td>
                                    	        <td></td>
                                    		</tr>
                                    		<tr>
                                    			<td class="esp">Condi&ccedil;&otilde;es de acondicionamento</td>
                                    			<td><?=$this->form->getElement('condicoes_acondicionamento')->setDecorators(array('ViewHelper'));?></td>
                                    		</tr>
                                    		<tr>
                                    			<td class="esp">Informa&ccedil;&atilde;o do r&oacute;tulo</td>
                                    			<td><?=$this->form->getElement('informacao_rotulo')->setDecorators(array('ViewHelper'));?></td>
                                    		</tr>
                                    	</table>
    								</div>
								</div>
							</div>
							<div class="tab-pane space" id="tab3">
							    <p>Decisão Tomada</p>
    							<table class="table table-striped txtsmall">
                                	<tr>
                                		<td><b>Aprovado:</b></td>
                                		<td class="esp"><?=$this->form->getElement('aprovado')->setDecorators(array('ViewHelper'));?></td>
                                		<td class="esp"><b>Data Aprova&ccedil;&atilde;o:</b></td>
                                		<td><?=$this->form->getElement('data')->setDecorators(array('ViewHelper'));?></td>
                                		<td class="esp"><b>Aprovado Por:</b></td>
                                		<td><?=$this->form->getElement('aprovado_por')->setDecorators(array('ViewHelper'));?></td>
                                	</tr>
                                </table>
							</div>
							<div class="tab-pane space" id="tab4">
							    <p>Amostragem</p>
							    <table class="table table-striped txtsmall">
                                		<tr>
                                			<td>N&ordm; Embalagens Inpeccionadas:</td>
                                			<td><?=$this->form->getElement('embalagens_inspeccionadas')->setDecorators(array('ViewHelper'));?></td>
                                		</tr>
                                		<tr>
                                			<td>N&ordm; Defeitos Maiores</td>
                                			<td><?=$this->form->getElement('defeitos_maiores')->setDecorators(array('ViewHelper'));?></td>
                                		</tr>
                                		<tr>
                                			<td>N&ordm; Defeitos Menores</td>
                                			<td><?=$this->form->getElement('defeitos_menores')->setDecorators(array('ViewHelper'));?></td>
                                		</tr>
                                	</table>
							</div>
							<div class="tab-pane space" id="tab5">
							    <p>Observa&ccedil;&otilde;es:</p>
	                            <?=$this->form->getElement('obs')->setDecorators(array('ViewHelper'));?>
							</div>
						 </div>
					</div>
					<!--/span-->
                </div>
				<!--/row-->

			</div>
			<!--/span-->
		</div>
		<!--/row-->
<div class="form_boletins_submit">
<?=$this->form->getElement('submit')->setDecorators(array('ViewHelper'));?>
</div>
		<hr>

		

	</div>
	<!--/.fluid-container-->
</form>


<?php endif;?>
<script type="text/javascript" src="/js/boletim/verify.js"></script>