<?php echo $this->doctype();?>
<html lang="pt">
<head>
<?php echo $this->headMeta();?>
<?php echo $this->headScript();?>
<?php echo $this->headLink();?>
<?php echo $this->headTitle();?>
<?php echo $this->JSHelper()?>
<link rel="stylesheet" type="text/css" href="http://cdn.fterceiro.pt/library/plugins/qtip2/jquery.qtip.min.css" />
<script type="text/javascript" src="http://cdn.fterceiro.pt/library/plugins/qtip2/jquery.qtip.min.js"></script>
</head>
<body>
<?=$this->Navbar();?>
<?php echo $this->layout()->content; ?>
</body>
</html>
