<div class="container-fluid mywhite">
	<div class="row-fluid">
		<div class="span12 ">
		    <?php if (count($this->boletins) > 0):?>
		    <h3><i class="icon-file-alt"></i> Boletins Análise Bluepharma para enviar</h3>
			<table class="table table-striped txtsmall">
				<tr>
					<th><i class="icon-list-alt"></i> Bol. Nº</th>
					<th><i class="icon-user"></i> Cliente</th>
					<th><i class="icon-folder-close"></i> Produto</th>
					<th><i class="icon-edit"></i> Editar</th>
					<th><i class="icon-trash"></i> Apagar</th>
				</tr>
			     <?php foreach ($this->boletins as $boletim):?>
			     <?php $uid = uniqid();?>
			    <tr>
					<td><i class="icon-print icon-black"></i> <a href="/boletim/renderpdf/<?=$boletim['id'];?>"><?=$boletim['id'];?></a></td>
					<?php if($boletim['cliente'] == "Bluepharma-Ind. Farmac. SA" && $this->ck->getEmailStatus($boletim['id']) == 0):?>
					<td><?=$boletim['cliente']?> <i class="icon-envelope icon-black"  onclick="sendmail('<?=$boletim['id'];?>')" id="mailicon-<?=$boletim['id'];?>" style="cursor:pointer;"></i><span id="loading-animation<?=$boletim['id'];?>"></span></td>
					<?php else:?>
					<td><?=$boletim['cliente']?></td>
					<?php endif;?>
					<td><i class="icon-picture icon-black" id="thumb-<?=$boletim['id']?>-<?=$uid?>" onmouseover="mypopover('<?=$boletim['id']?>-<?=$uid?>');" style="cursor:pointer;"></i>&nbsp;<?=utf8_encode($boletim['produto'])?><span class="pull-right"><a href="http://embalagem.intranet.fterceiro.pt/obra/<?=$boletim['obra']?>" target="_blank"><i class="icon-external-link-sign"></i></a></span></td>
					<td><a class="btn btn-mini" href="#authModalEdit" data-toggle="modal" data-target="#authModal-<?=$boletim['id'];?>">Editar</a>
					<td><a id="btn-<?=$boletim['id'];?>" class="btn btn-mini btn-danger" href="#authModalRemove" data-toggle="modal" data-target="#authModal-<?=$boletim['id'];?>-remove">Apagar</a>
				</tr>
			    <?php endforeach;?>
			    
			</table>
			<div class="pagination-div">
			<?=$this->paginationControl($this->boletins, 'Sliding', 'pagination/pagination.phtml');?>
			</div>
			<?php else:?>
	             <p>&nbsp;</p>
	            <?=$this->Flashinfo('info', 'Não existe nenhum boletim para esta data.');?>
	        <?php endif;?>
		</div>
	</div>
</div>

<?php echo $this->partialLoop('partials/auth.phtml', $this->boletins) ?>
<?php echo $this->partialLoop('partials/delete.phtml', $this->boletins) ?>

<script type="text/javascript" src="/js/ajax/mail.js"></script>
