<div class="modal" id="authModal-<?=$this->id;?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none;">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel"><i class="icon-user"></i> Autenticação</h3>
	</div>
	<div class="modal-body">
	<span id="error-mgs-passwd-modal-<?=$this->id;?>"></span>
	 <div class="alert alert-info"><i class="icon-lock"></i><b> Recurso protegido.</b><br> Precisa de estar autenticado para proceder às alterações.</div>
		<p>Insira a sua password:</p>
		<form class="form-inline" method="post" action="/boletim/edit" onsubmit="return validatePasswd('<?=$this->id;?>')" >
          <input type="password" name="password" id="password-auth-<?=$this->id;?>" class="input-small" placeholder="password" />
          <input type="hidden" id="bolid" name="bolid" value="<?=$this->id;?>" />
          <input type="hidden" id="searchdate" name="searchdate" value="<?=$this->partialLoop()->view->searchdate;?>" />
          <input type="hidden" id="type" name="type" value="bydate" />
  <button type="submit" class="btn btn-primary">Editar Boletim</button>
</form>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
	</div>
</div>
<script type="text/javascript">
    $("#authModal-<?=$this->id;?>").on('shown.modal', function (e) {
        $("#password-auth-<?=$this->id;?>").focus();
    });
</script>
