<div class="modal" id="authModal-<?=$this->id;?>-remove" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none;">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"
			aria-hidden="true">×</button>
		<h3 id="myModalLabel"><i class="icon-user"></i> Autenticação</h3>
	</div>
	<div class="modal-body">
	<span id="error-mgs-passwd-modal-del-<?=$this->id;?>"></span>
	    <div class="alert alert-error"><b><i class="icon-exclamation-sign"></i> Atenção!</b><br> Vai apagar permanentemente o Boletim de Análise Nº<?=$this->id;?>.</div>
		<p>Insira a sua password:</p>
		<form class="form-inline" method="post" action="/boletim/delete/" onsubmit="return validatePasswdDel('<?=$this->id;?>')">
          <input type="password" name="password" id="password-del-<?=$this->id;?>" class="input-small" placeholder="password" />
          <input type="hidden" id="bolid" name="bolid" value="<?=$this->id;?>" />
          <input type="hidden" id="searchdate" name="searchdate" value="<?=$this->partialLoop()->view->searchdate;?>" />
          <input type="hidden" id="type" name="type" value="<?=$this->partialLoop()->view->type;?>" />
  <button type="submit" class="btn btn-danger">Apagar boletim</button>
</form>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
	</div>
</div>
<script type="text/javascript">
    $("#authModal-<?=$this->id;?>-remove").on('shown.modal', function (e) {
        $("#password-del-<?=$this->id;?>").focus();
    });
</script>